name: Node.js Server Workflow

on: [push, pull_request]

jobs:
  run-server:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Check and install Node.js 22.10 and NPM
        run: |
          required_node_version="22.10.0"
          required_npm_version="9.0.0"

          check_version() {
            local current_version="$1"
            local required_version="$2"
            dpkg --compare-versions "$current_version" ge "$required_version"
          }

          node_path=$(which node || true)
          npm_path=$(which npm || true)

          if [ -z "$node_path" ] || [ -z "$npm_path" ]; then
              echo "Node.js or NPM not found. Installing them..."
              sudo apt update
              sudo apt install -y curl
              curl -fsSL https://deb.nodesource.com/setup_22.x | sudo -E bash -
              sudo apt-get install -y nodejs
          fi

          node_version=$("$node_path" -v | tr -d 'v' || echo "0.0.0")
          npm_version=$("$npm_path" -v || echo "0.0.0")

          if ! check_version "$node_version" "$required_node_version"; then
              echo "Node.js version ($node_version) is not compatible. Installing the required version..."
              curl -fsSL https://deb.nodesource.com/setup_22.x | sudo -E bash -
              sudo apt-get install -y nodejs
          fi

          if ! check_version "$npm_version" "$required_npm_version"; then
              echo "NPM version ($npm_version) is not compatible. Updating..."
              sudo npm install -g npm@"$required_npm_version"
          fi

          echo "Adding Node.js to PATH if necessary..."
          node_bin_path=$(dirname "$(which node)")
          export PATH="$PATH:$node_bin_path"

      - name: Install dependencies
        run: npm install

      - name: Start server
        run: |
          npm run server &
          sleep 10
          pkill -f "node"  # Oprește serverul după 10 secunde

      - name: Verify server was stopped
        run: |
          if pgrep -f "node"; then
            echo "Server is still running. This is unexpected."
            exit 1
          else
            echo "Server stopped successfully after 10 seconds."
          fi